### PR TITLE
Remove filling and mixer parsering for REKS and adjust energy writing for case of REKS

### PR DESCRIPTION
**Pull request by bhourahine**
Now when using REKS, does not look for filling{} and mixer{} block in the input and prints total energy instead of Mermin free energy as TS=0 for REKS.

### CODE REVIEW

**Comment by inseonglee** [comment]
For mermin, zero, Gibbs, force-related energies, these values are set in the following routines.

main.F90 file : line 6681 - 6685
reksen.F90 file : line 430 - 433
mainio.F90 file : 4861 - 4873

Should these lines be removed?

**Comment by bhourahine** [comment]
> Should these lines be removed?

The change in mainio.F90 is to only print quantities if the electron entropy (Mermin, zero temperature) and chemical potential (Gibbs, well to be more accurate, the Helmholtz energy) are defined. Storing them internally is probably OK for the moment, but I'll check the lines you list.

Regarding the ifort19.1 behaviour, this seems to possibly be an openMP bug in the compiler (still investigating). Both the real and reciprocal space parts are incorrect with 19.3 for a release build but pass for a debug build. If the OMP directives are all remove in that routine and some write statements added, all tests pass with ifort19.3 with release settings (but removing the write statements causes a fail).

**Comment by inseonglee** [comment]
@bhourahine I see, then do you remove the OMP directive in that routine? But in this case it may show large cost when the number of external charges increases.

Also, if the check for energies is finished, then I will merge this PR.

**Comment by bhourahine** [comment]
@inseonglee I'm starting to think its related to this [bug](https://community.intel.com/t5/Intel-Fortran-Compiler/Apparent-OMP-bugs-in-ifort-19-xx/m-p/1138483#M136441) as reducing optimization to -O2 seems to stop the behaviour. This might be why this was not previously appearing, as the default was -O2.

**Comment by bhourahine** [comment]
> Should these lines be removed?

I've checked them over and these can remain for the upcoming merge and release, so will merge this into your branch as well as the change to -O2 behaviour for the compiler from [#556](https://github.com/dftbplus/dftbplus/pull/556) in the main repository.

**Pull request merged**
